In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('clean_data.csv')

In [3]:
data.head()

,price,area,status,bhk,bathroom,age,location,builder
0,37.49,872,Ready to move,2,NaN,1.0,Sembakkam,MP Developers
1,93.54,1346,Under Construction,3,2.0,NaN,Selaiyur,DAC Promoters
2,151.00,2225,Under Construction,3,NaN,0.0,Mogappair,Casagrand Builder Private Limited
3,49.00,1028,Ready to move,2,2.0,3.0,Ambattur,Dugar Housing Builders
4,42.28,588,Under Construction,2,1.0,0.0,Pallavaram,Radiance Realty Developers India Ltd

In [4]:
data.shape

(2620, 8)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2620 entries, 0 to 2619
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     2620 non-null   float64
 1   area      2620 non-null   int64
 2   status    2620 non-null   object
 3   bhk       2620 non-null   int64
 4   bathroom  1403 non-null   float64
 5   age       1729 non-null   float64
 6   location  2620 non-null   object
 7   builder   2620 non-null   object
dtypes: float64(3), int64(2), object(3)
memory usage: 163.9+ KB

In [7]:
for column in data.columns:
    print(data[column].value_counts())
    print("*"*20)

price
398.00    41
70.00     37
35.00     31
53.00     27
28.00     26
          ..
66.30      1
23.47      1
66.35      1
23.26      1
31.50      1
Name: count, Length: 1281, dtype: int64
********************
area
2650    41
1200    35
1027    29
1000    29
800     28
        ..
583      1
1346     1
1059     1
1439     1
898      1
Name: count, Length: 1011, dtype: int64
********************
status
Ready to move         1487
Under Construction    1133
Name: count, dtype: int64
********************
bhk
2    1367
3     895
1     177
4     108
5      67
6       4
8       2
Name: count, dtype: int64
********************
bathroom
2.0    796
3.0    395
1.0    125
5.0     49
4.0     33
6.0      4
7.0      1
Name: count, dtype: int64
********************
age
0.0     942
3.0     260
1.0     235
4.0     100
2.0      72
5.0      60
6.0      31
9.0      11
7.0       8
11.0      3
12.0      2
13.0      1
16.0      1
17.0      1
8.0       1
32.0      1
Name: count, dtype: int64
********************
location
Veppampattu         149
Pammal              139
Medavakkam          111
Sholinganallur       99
Perungudi            88
                   ...
Jeth Nagar            1
Sevvapet              1
Gokulapuram           1
Iyyapa Nagar          1
Kil Ayanambakkam      1
Name: count, Length: 178, dtype: int64
********************
builder
seller                               484
MC Foundation                        232
Appaswamy Real Estate                109
Propsource Realty Private Limited     79
Radiance Realty Developers            62
                                    ...
Prop Mart Technologies                 1
S Suresh Kumar                         1
Yadhav constructions real estates      1
MAXWORTH PROPERTIES                    1
Evrostos Properties                    1
Name: count, Length: 135, dtype: int64
********************

In [8]:
data.isna().sum()

price          0
area           0
status         0
bhk            0
bathroom    1217
age          891
location       0
builder        0
dtype: int64

In [9]:
data.describe()

             price         area          bhk     bathroom          age
count  2620.000000  2620.000000  2620.000000  1403.000000  1729.000000
mean     93.834683  1282.925191     2.443893     2.359230     1.355119
std     113.609349   692.566319     0.811984     0.844951     2.102682
min      12.830000   300.000000     1.000000     1.000000     0.000000
25%      42.000000   877.000000     2.000000     2.000000     0.000000
50%      61.735000  1091.500000     2.000000     2.000000     0.000000
75%      90.000000  1471.250000     3.000000     3.000000     3.000000
max    1422.000000  6700.000000     8.000000     7.000000    32.000000

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2620 entries, 0 to 2619
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     2620 non-null   float64
 1   area      2620 non-null   int64
 2   status    2620 non-null   object
 3   bhk       2620 non-null   int64
 4   bathroom  1403 non-null   float64
 5   age       1729 non-null   float64
 6   location  2620 non-null   object
 7   builder   2620 non-null   object
dtypes: float64(3), int64(2), object(3)
memory usage: 163.9+ KB

In [11]:
data['location'].value_counts()

location
Veppampattu         149
Pammal              139
Medavakkam          111
Sholinganallur       99
Perungudi            88
                   ...
Jeth Nagar            1
Sevvapet              1
Gokulapuram           1
Iyyapa Nagar          1
Kil Ayanambakkam      1
Name: count, Length: 178, dtype: int64

In [12]:
data.drop(columns=['builder'], inplace=True)

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2620 entries, 0 to 2619
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     2620 non-null   float64
 1   area      2620 non-null   int64
 2   status    2620 non-null   object
 3   bhk       2620 non-null   int64
 4   bathroom  1403 non-null   float64
 5   age       1729 non-null   float64
 6   location  2620 non-null   object
dtypes: float64(3), int64(2), object(2)
memory usage: 143.4+ KB

In [14]:
data['bhk'].value_counts()

bhk
2    1367
3     895
1     177
4     108
5      67
6       4
8       2
Name: count, dtype: int64

In [15]:
data['bathroom'].value_counts()

bathroom
2.0    796
3.0    395
1.0    125
5.0     49
4.0     33
6.0      4
7.0      1
Name: count, dtype: int64

In [16]:
data['bathroom'] = data['bathroom'].fillna(data['bathroom'].median())

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2620 entries, 0 to 2619
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     2620 non-null   float64
 1   area      2620 non-null   int64
 2   status    2620 non-null   object
 3   bhk       2620 non-null   int64
 4   bathroom  2620 non-null   float64
 5   age       1729 non-null   float64
 6   location  2620 non-null   object
dtypes: float64(3), int64(2), object(2)
memory usage: 143.4+ KB

In [18]:
data['area'].value_counts()

area
2650    41
1200    35
1027    29
1000    29
800     28
        ..
583      1
1346     1
1059     1
1439     1
898      1
Name: count, Length: 1011, dtype: int64

In [19]:
data['price_per_sqft'] = data['price']*100000/data['area']

In [20]:
data['price_per_sqft']

0       4299.311927
1       6949.479941
2       6786.516854
3       4766.536965
4       7190.476190
           ...
2615    3666.666667
2616    3666.666667
2617    3750.000000
2618    3705.882353
2619    3777.777778
Name: price_per_sqft, Length: 2620, dtype: float64

In [21]:
data.describe()

,price,area,bhk,bathroom,age,price_per_sqft
count,2620.000000,2620.000000,2620.000000,2620.000000,1729.000000,2620.000000
mean,93.834683,1282.925191,2.443893,2.192366,1.355119,6387.418466
std,113.609349,692.566319,0.811984,0.643660,2.102682,3409.167048
min,12.830000,300.000000,1.000000,1.000000,0.000000,1743.119266
25%,42.000000,877.000000,2.000000,2.000000,0.000000,4600.000000
50%,61.735000,1091.500000,2.000000,2.000000,0.000000,5417.177914
75%,90.000000,1471.250000,3.000000,2.000000,3.000000,6645.812201
max,1422.000000,6700.000000,8.000000,7.000000,32.000000,26086.956522

In [23]:
data.drop(columns=['age'], inplace=True)

In [24]:
data.describe()

             price         area          bhk     bathroom  price_per_sqft
count  2620.000000  2620.000000  2620.000000  2620.000000     2620.000000
mean     93.834683  1282.925191     2.443893     2.192366     6387.418466
std     113.609349   692.566319     0.811984     0.643660     3409.167048
min      12.830000   300.000000     1.000000     1.000000     1743.119266
25%      42.000000   877.000000     2.000000     2.000000     4600.000000
50%      61.735000  1091.500000     2.000000     2.000000     5417.177914
75%      90.000000  1471.250000     3.000000     2.000000     6645.812201
max    1422.000000  6700.000000     8.000000     7.000000    26086.956522

In [25]:
data['location'].value_counts()

location
Veppampattu         149
Pammal              139
Medavakkam          111
Sholinganallur       99
Perungudi            88
                   ...
Jeth Nagar            1
Sevvapet              1
Gokulapuram           1
Iyyapa Nagar          1
Kil Ayanambakkam      1
Name: count, Length: 178, dtype: int64

In [26]:
data.describe()

             price         area          bhk     bathroom  price_per_sqft
count  2620.000000  2620.000000  2620.000000  2620.000000     2620.000000
mean     93.834683  1282.925191     2.443893     2.192366     6387.418466
std     113.609349   692.566319     0.811984     0.643660     3409.167048
min      12.830000   300.000000     1.000000     1.000000     1743.119266
25%      42.000000   877.000000     2.000000     2.000000     4600.000000
50%      61.735000  1091.500000     2.000000     2.000000     5417.177914
75%      90.000000  1471.250000     3.000000     2.000000     6645.812201
max    1422.000000  6700.000000     8.000000     7.000000    26086.956522

In [27]:
(data['area']/data['bhk']).describe()

count    2620.000000
mean      517.649752
std       147.914705
min       250.000000
25%       427.625000
50%       499.583333
75%       579.125000
max      1675.000000
dtype: float64

In [28]:
data = data[((data['area']/data['bhk'])>=300)]
data.describe()

             price         area          bhk     bathroom  price_per_sqft
count  2593.000000  2593.000000  2593.000000  2593.000000     2593.000000
mean     94.462688  1289.801774     2.446587     2.197069     6396.745568
std     114.029166   692.736437     0.814806     0.642591     3422.929203
min      12.830000   300.000000     1.000000     1.000000     1743.119266
25%      42.180000   885.000000     2.000000     2.000000     4606.060606
50%      62.000000  1100.000000     2.000000     2.000000     5417.177914
75%      90.290000  1478.000000     3.000000     2.000000     6640.625000
max    1422.000000  6700.000000     8.000000     7.000000    26086.956522

In [29]:
data.shape

(2593, 7)

In [30]:
def remove_outliers_sqft(df):
    df_output = pd.DataFrame()
    for key,subdf in df.groupby('location'):
        m=np.mean(subdf.price_per_sqft)
        st=np.std(subdf.price_per_sqft)
        gen_df=subdf[(subdf.price_per_sqft>(m-st)) & (subdf.price_per_sqft<=(m+st))]
        df_output=pd.concat([df_output,gen_df], ignore_index=True)
    return df_output
data = remove_outliers_sqft(data)
data.describe()

             price         area          bhk     bathroom  price_per_sqft
count  1926.000000  1926.000000  1926.000000  1926.000000     1926.000000
mean     92.304772  1256.178609     2.434060     2.192627     6356.685034
std     114.185030   612.653176     0.779985     0.624826     3421.851599
min      12.830000   300.000000     1.000000     1.000000     2769.230769
25%      42.017500   875.250000     2.000000     2.000000     4750.000000
50%      60.565000  1080.000000     2.000000     2.000000     5326.776628
75%      86.402500  1450.000000     3.000000     2.000000     6498.915772
max    1422.000000  6617.000000     6.000000     5.000000    22018.739353

In [31]:
data.shape

(1926, 7)

In [32]:
data

,price,area,status,bhk,bathroom,location,price_per_sqft
0,82.00,960,Ready to move,2,2.0,Adambakam,8541.666667
1,77.80,890,Ready to move,2,2.0,Adambakam,8741.573034
2,82.00,1000,Ready to move,2,2.0,Adambakam,8200.000000
3,87.00,1015,Under Construction,2,2.0,Adambakam,8571.428571
4,78.00,954,Ready to move,2,2.0,Adambakam,8176.100629
...,...,...,...,...,...,...,...
1921,85.00,1621,Ready to move,3,3.0,tambaram west,5243.676743
1922,66.08,1180,Ready to move,3,3.0,tambaram west,5600.000000
1923,57.12,1020,Ready to move,2,2.0,tambaram west,5600.000000
1924,52.08,930,Ready to move,2,2.0,tambaram west,5600.000000
1925,50.40,900,Ready to move,2,2.0,tambaram west,5600.000000

In [34]:
data.drop(columns=['price_per_sqft'], inplace=True)

In [35]:
data.head()

   price  area              status  bhk  bathroom   location
0   82.0   960       Ready to move    2       2.0  Adambakam
1   77.8   890       Ready to move    2       2.0  Adambakam
2   82.0  1000       Ready to move    2       2.0  Adambakam
3   87.0  1015  Under Construction    2       2.0  Adambakam
4   78.0   954       Ready to move    2       2.0  Adambakam

In [36]:
data.to_csv("Cleaned_data.csv")

In [37]:
X = data.drop(columns=['price'])
y = data['price']

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [39]:
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=0)

In [40]:
print(X_train.shape)
print(X_test.shape)

(1540, 5)
(386, 5)

In [53]:
column_trans = make_column_transformer((OneHotEncoder(sparse_output=False, handle_unknown='ignore')
, ['status','location']), remainder='passthrough')

In [54]:
scaler  =StandardScaler()

In [55]:
lr = LinearRegression()

In [56]:
pipe = make_pipeline(column_trans, scaler, lr)

In [57]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['status', 'location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [58]:
y_pred_lr = pipe.predict(X_test)

In [60]:
r2_score(y_test, y_pred_lr)

0.9431360530544549

In [61]:
lasso = Lasso()

In [62]:
pipe = make_pipeline(column_trans, scaler, lasso)

In [63]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['status', 'location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [65]:
y_pred_lasso = pipe.predict(X_test)
r2_score(y_test, y_pred_lasso)

0.9302016096666421

In [66]:
ridge = Ridge()

In [68]:
pipe = make_pipeline(column_trans, scaler, ridge)

In [69]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['status', 'location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [70]:
y_pred_ridge = pipe.predict(X_test)

In [71]:
r2_score(y_test, y_pred_ridge)

0.9430588785221334

In [72]:
import pickle

In [73]:
pickle.dump(pipe, open('RidgeModel.pkl', 'wb'))